app-proxy:
  image: app-proxy
  ports:
    - 9000:9000
  links:
    - app-backend
app-backend:
  image: app-backend
  links:
    - postgres
    - redis
  environment:
    DATABASE_HOST: postgres
    DATABASE_PORT: 5432
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_NAME: app_backend
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 8
worker:
  image: app-backend
  links:
    - postgres
    - redis
  environment:
    DATABASE_HOST: postgres
    DATABASE_PORT: 5432
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_NAME: app_backend
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 8
  command: bundle exec sidekiq
postgres:
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: app_backend
  image: postgres
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
redis:
  image: redis
